# NAME: JIAXUAN XUE
# EMAIL: nimbusxue1015@g.ucla.edu
# ID: 705142227

default:
	gcc -g -Wall -Wextra -lz -o lab1b-client lab1b-client.c
	gcc -g -Wall -Wextra -lz -o lab1b-server lab1b-server.c

client:
	gcc -g -Wall -Wextra -lz -o lab1b-client lab1b-client.c

server: 
	gcc -g -Wall -Wextra -lz -o lab1b-server lab1b-server.c

clean:
	rm -f lab1b-705142227.tar.gz lab1b-client lab1b-server

dist:
	tar -czvf lab1b-705142227.tar.gz lab1b-server.c lab1b-client.c Makefile README


