# NAME: JIAXUAN XUE
# EMAIL: nimbusxue1015@g.ucla.edu
# ID: 705142227

default:
	tar -czvf lab4a-705142227.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README

clean:
	rm -f lab4a-705142227.tar.gz

dist:
	tar -czvf lab4a-705142227.tar.gz my_beaglebone.jpg connected.png copy.png build_run.png git.png Makefile README


