# NAME: JIAXUAN XUE
# EMAIL: nimbusxue1015@g.ucla.edu
# ID: 705142227

default:
	gcc -g -Wall -Wextra -o lab1a lab1a.c

clean:
	rm -f lab1a lab1a-705142227.tar.gz

dist:
	tar -czvf lab1a-705142227.tar.gz lab1a.c Makefile README


