# NAME: JIAXUAN XUE
# EMAIL: nimbusxue1015@g.ucla.edu
# ID: 705142227

default:
	gcc -g -Wall -Wextra -o lab0 lab0.c

check: default
	./check.sh
clean:
	rm -f lab0 lab0-705142227.tar.gz

dist:
	tar -czvf lab0-705142227.tar.gz lab0.c Makefile backtrace.png breakpoint.png README check.sh


